### PR TITLE
support for transferables

### PR DESCRIPTION
**Pull request by FluffyDiscord**

### CODE REVIEW

**Comment by dumbmatter** [comment]
Thanks! This looks like a good PR. But honestly I've never used transferables before so I'm not totally sure if this is actually good. And even if it is, I'm not sure I want to increase the complexity for this feature that I won't use, since my main purpose in making promise-worker-bi was to use it myself.

So I recommend you either keep using your forked branch (I doubt promise-worker-bi will change very much) or release a forked version.

**Comment by FluffyDiscord** [comment]
Hi, for us this was a major performance difference. Passing buffer instead of a whole object for files was the only way to not lock up our client's UI. We are currently using my fork, but it would be great, to have it officially in.

**Comment by dumbmatter** [comment]
Oh yeah, I'm sure it's a huge difference maker in a situation like that, that's the whole point of transferables. I'm just not in that situation personally.

**Comment by dumbmatter** [comment]
I implemented something similar to this in version 4.1.0, sorry it took so long!

**Pull request closed without merging**
